# POST https://study.duyiedu.com/api/user/login HTTP/1.1
# content-type: application/json

# {
#   "loginId":"Sutee",
#   "loginPwd":"sutee"
# }

POST https://study.duyiedu.com/api/user/reg HTTP/1.1
content-type: application/json

{
  "loginId": "Suteeeee",
  "nickname": "Suteeeee",
  "loginPwd": "123123"
}